### ISSUE TITLE
Add responsiveness for mobile

### ISSUE THREAD

**Issue by ahmed-el-awad** [approxahmed/skills-in-review#2]
some things go out of bounds on mobile, and elements are too big at larger sizes

**Comment by Shabbir-Building** [comment]
Hey Ahmed Mudkip,

Hope you are doing well. I am interested on fix this issue. Please assign this issue to me.

Thanks,
shabbir

**Comment by ahmed-el-awad** [comment]
> Hey Ahmed Mudkip,
> 
> Hope you are doing well. I am interested on fix this issue. Please assign this issue to me.
> 
> Thanks, shabbir

Sure feel free to do so
Thank you

**Comment by Shabbir-Building** [comment]
Please first assign the issue to me.

**Comment by Shabbir-Building** [comment]
Thank you so much. I will get down to work as soon as I get back.

best,
Shabbir

**Comment by ahmed-el-awad** [comment]
> Thank you so much. I will get down to work as soon as I get back.
> 
> best, Shabbir

Take your time, thank you too

**Comment by Shabbir-Building** [comment]
Hey, I have updated the code. Please check this out.
